/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const Complaint = IDL.Record({
  'username' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Player = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Text,
  'gameLevel' : IDL.Nat,
  'registeredAt' : Time,
});
export const TournamentEntry = IDL.Record({
  'playerId' : IDL.Text,
  'gameLevel' : IDL.Nat,
  'playerName' : IDL.Text,
  'paymentNote' : IDL.Text,
});
export const PlayerRegistration = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Text,
  'gameLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(TournamentEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerPlayer' : IDL.Func([PlayerRegistration], [], []),
  'registerTournament' : IDL.Func([TournamentEntry], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendComplaint' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const Complaint = IDL.Record({
    'username' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Player = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Text,
    'gameLevel' : IDL.Nat,
    'registeredAt' : Time,
  });
  const TournamentEntry = IDL.Record({
    'playerId' : IDL.Text,
    'gameLevel' : IDL.Nat,
    'playerName' : IDL.Text,
    'paymentNote' : IDL.Text,
  });
  const PlayerRegistration = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Text,
    'gameLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(TournamentEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerPlayer' : IDL.Func([PlayerRegistration], [], []),
    'registerTournament' : IDL.Func([TournamentEntry], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendComplaint' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };