/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'body' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface ChatMessage {
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export interface Complaint {
  'username' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Player {
  'username' : string,
  'userId' : string,
  'gameLevel' : bigint,
  'registeredAt' : Time,
}
export interface PlayerRegistration {
  'username' : string,
  'userId' : string,
  'gameLevel' : bigint,
}
export type Time = bigint;
export interface TournamentEntry {
  'playerId' : string,
  'gameLevel' : bigint,
  'playerName' : string,
  'paymentNote' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getLeaderboard' : ActorMethod<[], Array<Player>>,
  'getPlayer' : ActorMethod<[string], Player>,
  'getTournaments' : ActorMethod<[], Array<TournamentEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postAnnouncement' : ActorMethod<[string, string, string], undefined>,
  'registerPlayer' : ActorMethod<[PlayerRegistration], undefined>,
  'registerTournament' : ActorMethod<[TournamentEntry], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string, string], undefined>,
  'sendComplaint' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];